spring.application.name=Student API
spring.datasource.url=jdbc:mysql://localhost:3306/studentDatabase
spring.datasource.username=root
spring.datasource.password=xEa2Y5Esbrg@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
